apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-ci-scxa
spec:
  # If we set workspaceVolume dynamicPVC() or workspaceVolume persistentVolumeClaimWorkspaceVolume() we need to add a
  # fsGroup 1000 to make the /home/jenkins/agent directory writable. Otherwise we get the following exception in the
  # jnlp container:
  # Exception in thread "main" java.io.IOException: The specified working directory should be fully accessible to the remoting executable (RWX): /home/jenkins/agent
  # The securityContext in the pod is inherited, as it becomes the default pod template
  securityContext:
    fsGroup: 1000
  containers:
    - name: openjdk
      image: openjdk:11
      resources:
        requests:
          memory: "1.5Gi"
        limits:
          memory: "2Gi"
      env:
      - name: GRADLE_OPTS
        value: "-Dorg.gradle.daemon=false"
      - name: GRADLE_RO_DEP_CACHE
        value: "/root/gradle-ro-dep-cache"
      command:
      - sleep
      args:
      - 99d
    - name: postgres
      image: postgres:10-alpine
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
