version: "3.6"

services:
  #### SolrCloud
  scxa-zk-1:
    image: zookeeper:3.4.14
    container_name: scxa-zk-1
    networks:
      - scxa
    ports:
      - "2181:2181"
    restart: always
    volumes:
      - scxa-zk-1-data:/data
      - scxa-zk-1-datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=scxa-zk-2:2888:3888 server.3=scxa-zk-3:2888:3888

  scxa-zk-2:
    image: zookeeper:3.4.14
    container_name: scxa-zk-2
    networks:
      - scxa
    ports:
      - "2182:2181"
    restart: always
    volumes:
      - scxa-zk-2-data:/data
      - scxa-zk-2-datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=scxa-zk-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=scxa-zk-3:2888:3888

  scxa-zk-3:
    image: zookeeper:3.4.14
    container_name: scxa-zk-3
    networks:
      - scxa
    ports:
      - "2183:2181"
    restart: always
    volumes:
      - scxa-zk-3-data:/data
      - scxa-zk-3-datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=scxa-zk-1:2888:3888 server.2=scxa-zk-2:2888:3888 server.3=0.0.0.0:2888:3888

  scxa-solrcloud-1:
    image: solr:7.1.0
    container_name: scxa-solrcloud-1
    networks:
      - scxa
    ports:
      - "8983:8983"
    volumes:
      - scxa-solrcloud-1-data:/opt/solr/server/solr
      - $ATLAS_DATA_PATH/solrcloud/solr1:/var/backups/solr
    environment:
      - SOLR_HEAP=2g
      - SOLR_OPTS=-Denable.runtime.lib=true
      - ZK_HOST=scxa-zk-1:2181,scxa-zk-2:2181,scxa-zk-3:2181
    depends_on:
      - scxa-zk-1
      - scxa-zk-2
      - scxa-zk-3

  scxa-solrcloud-2:
    image: solr:7.1.0
    container_name: scxa-solrcloud-2
    networks:
      - scxa
    ports:
      - "8984:8983"
    volumes:
      - scxa-solrcloud-2-data:/opt/solr/server/solr
      - $ATLAS_DATA_PATH/solrcloud/solr2:/var/backups/solr
    environment:
      - SOLR_HEAP=2g
      - SOLR_OPTS=-Denable.runtime.lib=true
      - ZK_HOST=scxa-zk-1:2181,scxa-zk-2:2181,scxa-zk-3:2181
    depends_on:
      - scxa-zk-1
      - scxa-zk-2
      - scxa-zk-3

  #### PostgreSQL database
  scxa-postgres:
    image: postgres:10-alpine
    container_name: $POSTGRES_HOST
    networks:
      - scxa
    restart: always
    command: -c max_wal_size=2GB
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - scxa-pgdata:/var/lib/postgresql/data
      - $ATLAS_DATA_PATH/postgresql:/var/backups/postgresql

  scxa-flyway:
    image: flyway/flyway
    container_name: scxa-flyway
    networks:
      - scxa
    command: -url=jdbc:postgresql://$POSTGRES_HOST/$POSTGRES_DB -schemas=$POSTGRES_USER -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -connectRetries=60 migrate
    volumes:
      - ../schemas/flyway/scxa/:/flyway/sql
    depends_on:
      - scxa-postgres

  #### Web server and filesystem
  scxa-tomcat:
    image: tomcat:9-jdk11
    container_name: scxa-tomcat
    networks:
      - scxa
    environment:
      JPDA_ADDRESS: "*:8000"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ../webapps:/usr/local/tomcat/webapps
      - ./atlas-properties:/atlas-properties
      - $ATLAS_DATA_PATH/filesystem:/atlas-data
      - scxa-tomcat-conf:/usr/local/tomcat/conf
    depends_on:
      - scxa-postgres
      - scxa-solrcloud-1
      - scxa-solrcloud-2
    command: ["catalina.sh", "jpda", "run"]

volumes:
  scxa-zk-1-data:
    name: scxa-zk-1-data
  scxa-zk-1-datalog:
    name: scxa-zk-1-datalog
  scxa-zk-2-data:
    name: scxa-zk-2-data
  scxa-zk-2-datalog:
    name: scxa-zk-2-datalog
  scxa-zk-3-data:
    name: scxa-zk-3-data
  scxa-zk-3-datalog:
    name: scxa-zk-3-datalog
  scxa-solrcloud-1-data:
    name: scxa-solrcloud-1-data
  scxa-solrcloud-2-data:
    name: scxa-solrcloud-2-data
  scxa-pgdata:
    name: scxa-pgdata
  scxa-tomcat-conf:
    name: scxa-tomcat-conf

networks:
  scxa:
    name: scxa
